#!/bin/sh

ENVINIT_PATH="/sbin/evo-envinit"

while true; do
  echo "Please enter sonobot serial number:"
  read SN
  test "${SN}" -eq "${SN}" 2>/dev/null && break || echo "It is not a number!"
done

IP=$(( (${SN} % 5000) + 30 ))
echo "Sonobot IP address range is 172.16.${IP}.0/24"

echo "Applying configuration..."
mount -o remount,rw /

sed -i "s/sonobot-0000/sonobot-${SN}/" /etc/hostname
sed -i "s/sonobot-0000/sonobot-${SN}/" /etc/hosts
sed -i "s/172\.16\.0\./172\.16\.${IP}\./g" /etc/network/interfaces

[ -d ${ENVINIT_PATH} ] || exit
for script in ${ENVINIT_PATH}/*-*.sh; do
  ${script}
done

sync && mount -o remount,ro /

