#!/bin/sh

ENVINIT_PATH="/sbin/evo-envinit"
HWID_FILE="/etc/evohw"
HW_INSTALL="/usr/share/evohw/install.sh"

EVOHW=$(cat /etc/hostname | sed -E 's/(.+)-([0-9]+)/\1/')
EVOSN=$(cat /etc/hostname | sed -E 's/(.+)-([0-9]+)/\2/')

mkrw()
{
  mount -o remount,rw /
}

mkro()
{
  sync && mount -o remount,ro /
}

execscripts()
{
  [ -d ${ENVINIT_PATH} ] || exit
  for script in ${ENVINIT_PATH}/*-*.sh; do
    ${script}
  done
}

hw_install()
{
  if [ -x ${HW_INSTALL} ]; then
    ${HW_INSTALL} ${1} ${2}
  fi
}

hostconfig()
{
  echo "Reconfiguring from ${EVOHW}-${EVOSN} to ${1}-${2}..."
  ( sed -i "s/${EVOHW}-${EVOSN}/${1}-${2}/" /etc/hostname && \
    sed -i "s/${EVOHW}-${EVOSN}/${1}-${2}/" /etc/hosts ) && \
  echo ok || echo failed!
}

###
echo "Extracted from hostname: ${EVOHW} with SN: ${EVOSN}"

# Look in HWID_FILE
if [ -e ${HWID_FILE} ]; then
  EVOHW_ID=$(cat ${HWID_FILE} | sed -E 's/(.+)-([0-9]+)/\1/')
  EVOSN_ID=$(cat ${HWID_FILE} | sed -E 's/(.+)-([0-9]+)/\2/')
  echo "HWID_FILE : ${EVOHW} with SN: ${EVOSN}"
 
  if [ -n ${EVOHW_ID} -a -n ${EVOSN_ID} ]; then
    mkrw
    hostconfig ${EVOHW_ID} ${EVOSN_ID}
    execscripts
    hw_install ${EVOHW_ID} ${EVOSN_ID}
    mkro
    exit 0
  fi
else
  echo "HWID_FILE not found. Doing just basic setup."
  mkrw
  execscripts
  mkro
fi
