#!/bin/bash

rollback() {
    echo lxc startup error. set default IP
    set +e
    {
         rmmod iptable_nat
         rmmod veth
         rmmod bridge
    } 2> /dev/null
}

lxc_start() {

    mount -o remount,rw /dev/pts
    mount -o remount,rw /opt/lxc/sandbox/rootfs
    
    ifconfig br0 down 2> /dev/null && brctl delbr br0
    
    modprobe iptable_nat
    modprobe veth
    modprobe bridge
    
    if true; then
    if ifconfig eth0 > /dev/null 2>&1; then
        ifconfig eth0 down
        
        OLD_MAC=$(ifconfig eth0 | sed -n 's/.*HWaddr //p')
        MAC=$(evo-gen-mac)
        
        while [ "$OLD_MAC" == "$MAC" ]; do
        	MAC=$(evo-gen-mac -r)
        done
        
	if ! ifconfig eth0 hw ether $MAC; then
		echo "setup $MAC fail" >&2
		i=3
        	while [ $i -ne 0 ]; do
 			MAC=$(evo-gen-mac -r)
 		        [ "$OLD_MAC" == "$MAC" ] && continue
 		        
        		ifconfig eth0 hw ether $MAC && break 
        		
			echo "setup $MAC fail" >&2
        		sleep 1
        		i=$((i - 1))
        	done
        	if [ $i -eq 0 ]; then
			echo "cannot set MAC. fail" >&2
			exit 1
        	fi
 	fi
    fi
    fi
        
    brctl addbr br0
    ifconfig br0  0.0.0.0
	
    if ifconfig eth0 > /dev/null 2>&1; then
        brctl addif br0 eth0
        ifconfig eth0 0.0.0.0
    fi
    
    
    sed 's/MY_MAC/'"$OLD_MAC"/ /opt/lxc/sandbox/config > /tmp/lxc-config
    
    #lxc-start -d -n sandbox -P /opt/lxc/
    lxc-start -d -n sandbox -f /tmp/lxc-config
    sleep .2
    
    echo -n Waing sandbox start.
    DONE=false
    for i in $(seq 20); do
        if ifconfig vlxc 192.168.42.2 2>/dev/null; then
            DONE=true
            break
        fi
        echo -n .
        sleep .1
    done
    
    if ! $DONE; then
        echo " fail"
        exit 1
    fi
    echo " ok"
    
    route add default gw 192.168.42.1
    
    ifconfig br0  down; ifconfig eth0 down
    sleep 1
    ifconfig br0  up; ifconfig eth0 up
}

lxc_stop() {
    lxc-stop -n sandbox 2> /dev/null || true
    if ifconfig eth0 > /dev/null 2>&1; then
        brctl delif br0 eth0
        
        ifconfig eth0 down
        ifconfig eth0 hw ether $(fw_printenv|sed -n 's/ethaddr=//p')
        ifconfig eth0 $(sed -n 's/IPADDRDEF=//p' /etc/init.d/fastboot)
    fi
    ifconfig br0 down
    brctl delbr br0
    
    ifconfig eth0 down;
    sleep 1
    ifconfig eth0 up
}

set -e

trap 'rollback' ERR

case $1 in
    start) 
    	if ! lxc-info -n sandbox | grep -q 'pid:.*-1$'; then
    		echo "lxc already runned"
    		exit
    	fi
    	
    	lxc_start 
    	;;
    stop)
      lxc_stop  ;;
    restart)
    	lxc_stop
    	lxc_start 
        ;;
    *)     echo "Usage: $0 [start|stop|restart]" ;;
esac

