#!/bin/sh

case $1 in
    start)   evo-sandbox start ;;
    stop)    evo-sandbox stop  ;;
    restart) evo-sandbox start
    		 evo-sandbox stop  ;;
    status)  evo-sandbox status;;
    *)     echo "Usage: $0 [start|stop|restart]" ;;
esac

