#!/bin/sh

DROPBEAR_RSAKEY_DIR="/etc/dropbear"
DROPBEAR_RSAKEY="${DROPBEAR_RSAKEY_DIR}/dropbear_rsa_host_key"
OPENSSH_RSAKEY_DIR="/etc/ssh"
OPENSSH_RSAKEY="${OPENSSH_RSAKEY_DIR}/ssh_host_rsa_key"
ENVINIT_PATH="/sbin/evo-envinit"

case "$1" in
  start)
    # look for ssh/dropbear host keys
    # exit if found, remount root as rw otherwise
    if [ -e ${DROPBEAR_RSAKEY} -o -e ${OPENSSH_RSAKEY} ]; then
      echo "Host keys found, boot in normal mode"
      exit 0
    fi

    mount -o remount,rw /

    [ -d ${ENVINIT_PATH} ] || exit
    for script in ${ENVINIT_PATH}/*-*.sh; do
      ${script}
    done

    sync && mount -o remount,ro /
    ;;
  stop)
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    echo "."
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac
