#! /bin/sh 
#
# This is an init script for openembedded
# Copy it to /etc/init.d/monit and type
# > update-rc.d monit defaults 99
#
monit=/usr/bin/monit
pidfile=/var/run/monit.pid
grep -i ' / ' /etc/fstab | grep -qe '[, ] *ro[, ] *'
if [ $? -eq 0 ]; then
  monit_conf="/etc/monitrc-ro-rootfs"
else
  monit_conf="/etc/monitrc"
fi
monit_args="-c ${monit_conf}"

test -x "$monit" || exit 0

case "$1" in
  start)
    echo -n "Starting Monit"
    $monit $monit_args &
    RETVAL=$?
    echo "."
    ;;
  stop)
    echo -n "Stopping Monit"
    $monit quit
    RETVAL=$?
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    RETVAL=$?
    ;;
  status)
    $monit $monit_args status
    RETVAL=$?
    echo "."
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit $RETVAL

